version: "3"

services:

# django-backend
  app:
    # restart: always
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: > ## this command correpsonds to run
      sh -c "python manage.py wait_for_db && 
             python manage.py migrate &&
             python manage.py my_runserver 0.0.0.0:8000 "
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db

# database
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword

# react frontend
  # frontend:
  #   restart: always
  #   command: npm run dev
  #   container_name: frontend
  #   build:
  #     context: ./app/frontend/
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   stdin_open: true
  #   depends_on:
  #     - backend

